### ISSUE TITLE
Request: "Requirements", "How to install" and "How to run" sections please

### ISSUE THREAD

**Issue by GersonHMG** [BrandonBahret/tetris_ai#1]
I want to run this program, but every time I try, I get errors.

**Comment by BrandonBahret** [comment]
Hello,

Thank you for your interest in my Tetris AI project! I am happy to know
that someone shares my interest in the project. This project was laborious,
taking months to assemble its various modules, with uncertainty about
whether they would ultimately work together. As demonstrated in the YouTube
video, it did succeed – at least temporarily.

Please note that the initial implementation was rather basic, and the
feature detection code is now outdated due to alterations in the game
board's design. As my second attempt at manually coding a computer vision
routine, the code turned out to be quite fragile when confronted with
changes.

I apologize for the disorganized code you encountered. I didn't foresee
someone else trying to reconstruct the project from the redacted version.
To simplify the process, I have attached the full, unredacted program
<https://drive.google.com/file/d/1cKOrLn2u6Tg50Rq2AeWK8dgwBF4zo8Yo/view?usp=sharing>
as
a zip file for your examination.

Regrettably, the game developer banned my account after discovering my bot,
even though it was only used in solo game modes. As a suggestion, you might
want to use an emulator for the NES to avoid potential design changes,
since it's not a web app. It should be fairly easy to find a Tetris rom and
emulator online. This route is better since the game's appearance will
never be altered! This was also something I thought about doing even before
attempting Tetrio, in hindsight, I should've kept it simple!

Once again, thank you for taking the time to delve into my project. It has
been two years since I last worked on it, so I have forgotten many details.
However, if you have any specific questions, please feel free to reach out.


https://drive.google.com/file/d/1cKOrLn2u6Tg50Rq2AeWK8dgwBF4zo8Yo/view?usp=sharing

Oh, I just found some jupyter notebooks I was doodling in while working on
the project. Idk, maybe these are helpful?

https://drive.google.com/file/d/19oZ4t2ZZHCCWvawA-7ZuslisUh8KPI2n/view?usp=sharing

**Comment by GersonHMG** [comment]
Many thanks for sharing this information.
